### ISSUE TITLE
null: falseとかつけて欲しい感もある（カリキュラムにかけてないからあれなんだけども、、）

### ISSUE THREAD

**Issue by shibatadaiki** [YukiTamura14/the_way#18]
https://github.com/YukiTamura14/the_way/blob/abbf6b90c8e945b9ca35befcad80003a11c52f09/db/migrate/20180906085502_create_concerns.rb#L4

**Comment by YukiTamura14** [comment]
https://qiita.com/ayacai115/items/b87f11b6f9a72d970d0f
https://railsguides.jp/active_record_migrations.html
参考に、記述。セキリティが高くなるのか、もう少し深く調べたい。
