### ISSUE TITLE
このローカル変数のfavorite多分何にも使ってないから入らなさげ（カリキュラムがそうだったような気もするけどあれは今小林さんが修正中なので、、、）

### ISSUE THREAD

**Issue by shibatadaiki** [YukiTamura14/the_way#8]
https://github.com/YukiTamura14/the_way/blob/abbf6b90c8e945b9ca35befcad80003a11c52f09/app/controllers/favorites_controller.rb#L3

**Comment by YukiTamura14** [comment]
確かに。変数に入れる必要がなかったです。
