### ISSUE TITLE
この@likeって何に使ってる？？（ビューに値を渡さないのであればインスタンス変数を定義する意味は特にないので、ローカル変数で処理をするかもしくは変数を使わない処理にしてください）

### ISSUE THREAD

**Issue by shibatadaiki** [YukiTamura14/the_way#9]
https://github.com/YukiTamura14/the_way/blob/abbf6b90c8e945b9ca35befcad80003a11c52f09/app/controllers/likes_controller.rb#L6

**Comment by YukiTamura14** [comment]
je.erbのフォーマットに渡したいので、インスタンス変数にしています。
ローカルにすると渡せなくなってしまうので、このままで><
